#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const PUBLIC = path.join(ROOT, "public");

const CSS_SOURCES = [
  "src/web/css/tokens.css",
  "src/web/css/board.css",
  "src/web/css/voice.css",
  "src/web/css/auth.css",
  "src/web/css/onboard.css",
  "src/web/css/mobile.css",
  "src/web/css/shell.css"
];

function joinFiles(files, banner) {
  const sections = files.map((file) => {
    const full = path.join(ROOT, file);
    if (!fs.existsSync(full)) throw new Error(`Missing ${file}`);
    return fs.readFileSync(full, "utf8").trimEnd();
  });
  return `${banner}\n${sections.join("\n")}\n`;
}

function buildCss() {
  const target = path.join(PUBLIC, "css", "app.css");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  const content = joinFiles(
    CSS_SOURCES,
    "/* Regenerated by scripts/build-web.js from src/web/css. Do not edit directly. */"
  );
  fs.writeFileSync(target, content, "utf8");
  console.log(`Built ${path.relative(ROOT, target)} (${(content.length / 1024).toFixed(1)} kB)`);
}

function checkSources(files) {
  for (const file of files) {
    if (!fs.existsSync(path.join(ROOT, file))) {
      console.error(`Missing source: ${file}`);
      return false;
    }
  }
  return true;
}

function main(argv = process.argv.slice(2)) {
  if (argv.includes("--check")) {
    const ok = checkSources(CSS_SOURCES);
    return ok ? 0 : 1;
  }
  buildCss();
  return 0;
}

if (require.main === module) process.exitCode = main();

module.exports = { buildCss, main };
