#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const TARGET = path.join(ROOT, "public", "js", "canvas", "app.js");
const SOURCES = [
  "src/client/app/core.js",
  "src/client/app/core-ui-controls.js",
  "src/client/app/core-plugins.js",
  "src/client/app/canvas-tiles.js",
  "src/client/app/canvas-images.js",
  "src/client/app/canvas-widgets.js",
  "src/client/app/canvas-rendering.js",
  "src/client/app/canvas-text-editors.js",
  "src/client/app/persistence.js",
  "src/client/app/ai-runtime.js",
  "src/client/app/ai-rendering.js",
  "src/client/app/ai-drafts.js",
  "src/client/app/ui-bootstrap.js",
  "src/client/app/ui-talk-mode.js",
];
const BANNER = "// Regenerated by scripts/build-client.js from src/client/app. Prefer editing public/js/canvas/app.js for the live board.";

function compiledSource() {
  const sections = SOURCES.map(file => fs.readFileSync(path.join(ROOT, file), "utf8").trimEnd());
  return `${BANNER}\n${sections.join("\n")}\n`;
}

function main(argv = process.argv.slice(2)) {
  if (argv.includes("--check")) {
    for (const file of SOURCES) {
      const full = path.join(ROOT, file);
      if (!fs.existsSync(full)) {
        console.error(`Missing ${file}`);
        return 1;
      }
    }
    if (!fs.existsSync(TARGET)) {
      console.error("Missing public/js/canvas/app.js");
      return 1;
    }
    return 0;
  }
  const source = compiledSource();
  fs.writeFileSync(TARGET, source);
  console.log(`Built ${path.relative(ROOT, TARGET)} from ${SOURCES.length} source files.`);
  return 0;
}

if (require.main === module) process.exitCode = main();

module.exports = { BANNER, SOURCES, compiledSource, main };
