"use strict";
(() => {
  const SIZE = 20000,
    TILE = 512,
    INITIAL_VIEW_ZOOM = 1.5,
    EXPORT_MAX_DIMENSION = 16384,
    EXPORT_MAX_PIXELS = 64 * 1024 * 1024,
    MAX_ATLAS_WIDTH = 2048,
    MAX_ATLAS_HEIGHT = 1536,
    FOCUS_INSET_ENABLED = true,
    MAX_LASSO_POINTS = 4096,
    MAX_HISTORY = 30,
    DEFAULT_AUTO_DELAY = 5000,
    DEFAULT_AI_TIMEOUT = 260000,
    screen = document.querySelector("#screen"),
    view = document.querySelector("#viewport"),
    ctx = screen.getContext("2d"),
    animationLayer = document.querySelector("#animationLayer"),
    animationCtx = animationLayer.getContext("2d"),
    widgetLayer = document.querySelector("#widgetLayer"),
    summonLayer = document.querySelector("#summonLayer"),
    inkLayer = document.querySelector("#inkLayer"),
    inkCtx = inkLayer.getContext("2d"),
    interactionLayer = document.querySelector("#interactionLayer"),
    interactionCtx = interactionLayer.getContext("2d"),
    objectChromeLayer = document.querySelector("#objectChromeLayer"),
    animationControls = document.querySelector("#animationControls"),
    animationPlayPause = document.querySelector("#animationPlayPause"),
    animationRestart = document.querySelector("#animationRestart"),
    animationDelete = document.querySelector("#animationDelete"),
    pluginButton = document.querySelector("#pluginButton"),
    pluginPopover = document.querySelector("#pluginPopover"),
    pluginOptions = document.querySelector("#pluginOptions"),
    pluginClose = document.querySelector("#pluginClose"),
    pluginRefresh = document.querySelector("#pluginRefresh"),
    pluginLocalTab = document.querySelector("#pluginLocalTab"),
    pluginCreateTab = document.querySelector("#pluginCreateTab"),
    pluginServerTab = document.querySelector("#pluginServerTab"),
    pluginLocalPanel = document.querySelector("#pluginLocalPanel"),
    pluginCreatePanel = document.querySelector("#pluginCreatePanel"),
    pluginServerPanel = document.querySelector("#pluginServerPanel"),
    pluginLocalCount = document.querySelector("#pluginLocalCount"),
    pluginCatalogStatus = document.querySelector("#pluginCatalogStatus"),
    pluginCreateForm = document.querySelector("#pluginCreateForm"),
    pluginSimpleTemplate = document.querySelector("#pluginSimpleTemplate"),
    pluginTitle = document.querySelector("#pluginTitle"),
    pluginDocumentEditor = document.querySelector("#pluginDocumentEditor"),
    pluginDocumentBytes = document.querySelector("#pluginDocumentBytes"),
    pluginStylesEditor = document.querySelector("#pluginStylesEditor"),
    pluginStylesUploadButton = document.querySelector("#pluginStylesUploadButton"),
    pluginStylesUpload = document.querySelector("#pluginStylesUpload"),
    pluginStylesBytes = document.querySelector("#pluginStylesBytes"),
    pluginStylesPreview = document.querySelector("#pluginStylesPreview"),
    pluginDocumentStatus = document.querySelector("#pluginDocumentStatus"),
    pluginImprove = document.querySelector("#pluginImprove"),
    pluginSave = document.querySelector("#pluginSave"),
    status = document.querySelector("#status"),
    coords = document.querySelector("#coords"),
    debugList = document.querySelector("#debugEvents"),
    debugRequest = document.querySelector("#debugRequest"),
    embodiment = document.querySelector("#aiEmbodiment"),
    aiOrb = document.querySelector("#aiOrb"),
    aiRadial = document.querySelector("#aiRadial"),
    selectionOverlayLayer = document.querySelector("#selectionOverlayLayer"),
    selectionToolbar = document.querySelector("#selectionToolbar"),
    selectionTypesetButton = document.querySelector("#selectionTypesetBtn"),
    selectionDeleteButton = document.querySelector("#selectionDeleteBtn"),
    selectionCancelButton = document.querySelector("#selectionCancelBtn"),
    imagePickerButton = document.querySelector("#imagePickerBtn"),
    clipboardCopyButton = document.querySelector("#clipboardCopyBtn"),
    imagePickerInput = document.querySelector("#imagePickerInput"),
    imageEditBar = document.querySelector("#imageEditBar"),
    imagePlaceButton = document.querySelector("#imagePlaceBtn"),
    imageMergeButton = document.querySelector("#imageMergeBtn"),
    imageDeleteButton = document.querySelector("#imageDeleteBtn"),
    textEditorLayer = document.querySelector("#textEditorLayer"),
    textInputHint = document.querySelector("#textInputHint"),
    tourMain = document.querySelector("main"),
    tourLayer = document.querySelector("#tourLayer"),
    tourHighlight = document.querySelector("#tourHighlight"),
    tourCard = document.querySelector("#tourCard"),
    tourBadge = document.querySelector(".tour-badge"),
    tourProgress = document.querySelector("#tourProgress"),
    tourProgressTrack = document.querySelector("#tourProgressTrack"),
    tourProgressBar = document.querySelector("#tourProgressBar"),
    tourTitle = document.querySelector("#tourTitle"),
    tourBody = document.querySelector("#tourBody"),
    tourBackButton = document.querySelector("#tourBack"),
    tourNextButton = document.querySelector("#tourNext"),
    tourSkipButton = document.querySelector("#tourSkip"),
    changelogLayer = document.querySelector("#changelogLayer"),
    changelogDialog = document.querySelector("#changelogDialog"),
    changelogCloseButton = document.querySelector("#changelogClose"),
    changelogDoneButton = document.querySelector("#changelogDone"),
    settingsLayer = document.querySelector("#settingsLayer"),
    settingsBackdrop = document.querySelector("#settingsBackdrop"),
    settingsPanel = document.querySelector("#settingsPanel"),
    settingsButton = document.querySelector("#settingsBtn"),
    settingsCloseButton = document.querySelector("#settingsClose"),
    settingsAutoToggle = document.querySelector("#settingsAutoToggle"),
    summonToggle = document.querySelector("#summonToggle"),
    settingsTourButton = document.querySelector("#settingsTourBtn"),
    settingsChangelogButton = document.querySelector("#settingsChangelogBtn");
  const DRAW = window.LUMI6_DRAW || {};
  const SELECT = window.LUMI6_SELECTION || {};
  const TOUR = window.LUMI6_TOUR || {
    resolveInitialLanguage: (p, l) => p || l || "en",
    parseProgress: () => ({ seen: [] }),
    markSeen: (prog, ids) => ({ seen: Array.from(new Set([...(prog?.seen || []), ...(ids || [])])) }),
    serializeProgress: (prog) => JSON.stringify(prog || { seen: [] }),
    rectHasArea: (rect) => Boolean(rect && rect.width > 0 && rect.height > 0),
    unionRects: (rects) => rects[0] || { left: 0, top: 0, right: 0, bottom: 0, width: 0, height: 0 },
    placeCoachmark: () => ({ left: 0, top: 0 }),
    unseenSteps: () => [],
    keyAction: () => null
  };
  const MIXED_TEXT = window.LUMI6_MIXED_TEXT || {};
  const ANIMATION = window.LUMI6_ANIMATION || {};
  const PLUGINS = window.LUMI6_PLUGINS || {
    parse: () => null
  };
  const SUMMON = window.LUMI6_SUMMON || {};
  const EFFORT_LEVELS = ["none", "low", "medium", "high", "max"],
    EFFORT_OPTIONS = ["config", ...EFFORT_LEVELS],
    TEXT_EDITOR_DEFAULT_WIDTH = 320,
    TEXT_EDITOR_DEFAULT_HEIGHT = 168,
    TEXT_EDITOR_MIN_WIDTH = 170,
    TEXT_EDITOR_MIN_HEIGHT = 96,
    TEXT_EDITOR_FONT_CSS = 17,
    TEXT_EDITOR_PREVIEW_INTERVAL_MS = 80,
    TEXT_EDITOR_FONT_FAMILY = "ui-rounded, system-ui, sans-serif",
    TEXT_INPUT_GUARD_MS = 500,
    TEXT_INPUT_MAX_LENGTH = 2000,
    MAX_VISIBLE_TEXT_BOXES = 50,
    MIXED_FORMULA_MAX_LENGTH = 512,
    AI_TEXT_MAX_LENGTH = 1000,
    COPY_FEEDBACK_MS = 1600,
    NAVIGATION_HINT_VISIBLE_MS = 10000,
    ANIMATION_CONTROLS_VISIBLE_MS = 10000;
  const MAX_SHARP_OVERLAY_PIXELS = 8000000,
    MAX_SHARP_OVERLAY_ITEM_PIXELS = 2500000,
    MAX_VISIBLE_ANIMATIONS = 100,
    MAX_VISIBLE_WIDGETS = 100,
    MAX_VISIBLE_IMAGES = 100,
    MAX_IMAGE_SOURCE_BYTES = 32 * 1024 * 1024,
    MAX_IMAGE_DIMENSION = 2048,
    MAX_IMAGE_PIXELS = 16 * 1024 * 1024,
    MAX_WIDGET_HTML_LENGTH = 200000,
    MAX_WIDGET_COPY_TEXT_LENGTH = 16000,
    MAX_DIAGRAM_SOURCE_BYTES = 100 * 1024,
    MAX_WIDGET_CONTENT_DIMENSION = 1000000,
    WIDGET_SNAPSHOT_TIMEOUT_MS = 12000;
  const PLUGIN_TEMPLATE_DOCUMENTS = Object.freeze({
    simple: `---
lumi6-plugin: 1
id: air-quality
name: Air Quality
version: 1
description: Show air quality for a place in a live canvas widget.
category: Environment
source: Public web API
connect:
recommended-refresh-seconds: 900
---

# Air Quality

Show air quality for a location.

## Output contract

Return exactly one html_widget command and no prose, with pluginId:"air-quality". Generate a complete responsive HTML document that uses the place from the user's request, displays the most important air-quality information clearly, and keeps the outer layout transparent.

## Runtime rules

The generated HTML must fetch data directly in the user's browser, own its refresh timer, and show loading, error, and last-update states. Improve with AI before saving so this draft gains exact browser-accessible API origins, endpoint URLs, parameters, response fields, and instructions for constructing and using those URLs inside the HTML.

## One-shot example

User writes "Show air quality for Tokyo", names a place, and points to an empty area. Produce one html_widget there that uses that place in its API requests and displays the resulting air-quality information in large readable type.`,
  });
  const PLUGIN_TEMPLATE_STYLES = Object.freeze({ simple:"" });
  const I18N = {
    en: {
      title: "Lumi6 | Handwritten AI Canvas",
      tagline: "Write across twenty thousand squares and summon knowledge",
      taglineArcane: "Interdisciplinary intuition, creative synthesis, and exploratory explanation",
      taglineScifi: "Engineering, programming, system design, and future-technology analysis",
      taglineResearch: "Mathematical physics, rigorous teaching, and verifiable code",
      taglineStudio: "A clean, focused studio for clear structure and practical answers",
      taglineIndic: "Knowledge, Indian culture, science, languages, and rich structural insights",
      taglineCanvasPro: "Professional whiteboard with dedicated AI teaching assistant drawer",
      language: "Language",
      theme: "Theme",
      themeArcane: "Arcane",
      themeScifi: "Sci-fi",
      themeResearch: "Research",
      themeStudio: "Studio",
      themeIndic: "Indic",
      themeCanvasPro: "Canvas Pro",
      themeFocusArcane: "Favors interdisciplinary insight, intuitive analogy, and creative exploration",
      themeFocusScifi: "Favors engineering, debugging, system design, and future technology",
      themeFocusResearch: "Favors mathematical physics, rigorous derivation, teaching, and code verification",
      themeFocusStudio: "Favors clean layout, concise structured answers, and practical next steps",
      themeFocusIndic: "Favors rich cultural synthesis, Indian knowledge systems, ancient science, literature, languages, and vibrant structured explanations",
      themeFocusCanvasPro: "Favors professional whiteboard tools and right-side ATLAS AI assistant",
      guideArcane: "Arcane knowledge crystal",
      guideScifi: "Holographic analysis core",
      guideResearch: "Einstein scientific mentor",
      guideStudio: "Studio assistant",
      guideIndic: "Indic AI knowledge guide",
      guideCanvasPro: "ATLAS AI Teaching Assistant",
      boardTools: "Board tools",
      hand: "Hand tool: move canvas and objects",
      pen: "Pen",
      eraser: "Eraser",
      select: "Lasso select",
      text: "Text input",
      textMixedMode: "Preview Markdown + LaTeX formatting",
      textMixedModeShort: "Preview",
      textEditMode: "Return to editing",
      textPreview: "Markdown and LaTeX preview",
      textConfirm: "Confirm text",
      textCancel: "Discard text",
      textPlaceholder: "Type text or a formula",
      textConfirmHint: "to confirm",
      textEmpty: "Enter some text first",
      textMixedModeError: "Mixed formatting was unavailable; plain text was inserted",
      textHelp: "Text formatting help",
      addImage: "Add image or photo",
      copyFromClipboard: "Copy text or image from clipboard",
      clipboardReading: "Reading clipboard...",
      clipboardTextAdded: "Clipboard text added. Move or resize the text box, then confirm.",
      clipboardUnsupported: "Clipboard format not supported. Copy plain text or an image.",
      clipboardReadFailed: "Could not read the clipboard. Allow clipboard access or use Ctrl/Cmd+V.",
      imageLoading: "Preparing image...",
      imageAdded: "Image added",
      imageSelected: "Editing image: drag the top handle to move, use edge handles to resize, or choose a side action",
      imageMerged: "Merged into canvas ink — the eraser now works on it",
      imageEditBarLabel: "Image actions",
      imagePlace: "Place image",
      imagePlaceHint: "Keep it as an image; use Hand and its top handle to edit again",
      imageMerge: "Merge into ink",
      imageMergeHint: "Fuse into the canvas; the eraser then works on it",
      imageDelete: "Delete image",
      imageDeleteHint: "Remove this image from the canvas",
      imageDeleted: "Image deleted",
      imageLimitReached: "Image limit reached (100). Delete an image before adding another.",
      imageTooLarge: "The selected image is too large (32 MB maximum)",
      imageUnsupported: "This image format could not be opened",
      imageImportFailed: "The image could not be added",
      textHelpTitle: "Markdown + LaTeX",
      textHelpClose: "Close text help",
      textHelpIntro: "Type normally; line breaks are preserved. Markdown and likely LaTeX are formatted automatically when confirmed; Preview shows the result.",
      textHelpMarkdown: "Use # for headings, - for lists, **text** for bold, and *text* for italic.",
      textHelpMath: "You may use $...$, but common bare TeX such as \\pi, \\frac{a}{b}, A_x, and \\sin(x) is recognized too.",
      textHelpConfirm: "Press Ctrl/Cmd + Enter to confirm.",
      textHelpExampleTitle: "Example",
      textHelpExample: "# Kinematics\n**Speed:** $v=\\frac{d}{t}$\n- Area: $A=\\pi r^2$",
      textHelpDone: "Got it",
      penSize: "Pen size",
      autoAI: "Auto AI",
      autoEnabled: "Auto ({delay}s)",
      autoDisabled: "Manual AI",
      autoDelay: "Auto AI delay",
      autoToolboxPending: "Auto AI paused: settle the open toolbox or trigger AI manually",
      aiTools: "AI tools",
      grid: "Canvas grid",
      gridOn: "Show canvas grid",
      gridOff: "Hide canvas grid",
      researchGridDefault: "Research grid (off by default)",
      font: "Font",
      aiFont: "AI font",
      reasoningEffort: "Reasoning effort",
      reasoningEffortDisplay: "Reasoning ({level})",
      effortConfigured: "Configured",
      effortConfiguredShort: "Conf",
      effortNone: "None",
      effortLow: "Low",
      effortMedium: "Medium",
      effortMediumShort: "Med",
      effortHigh: "High",
      effortMaximum: "Max",
      inkColor: "Ink color",
      fontRounded: "Rounded",
      fontHand: "Handwritten",
      fontSerif: "Classic serif",
      fontSans: "Sans serif",
      aiColor: "AI color",
      colorBlue: "Blue",
      colorBlack: "Ink black",
      colorRed: "Red",
      colorOrange: "Orange",
      colorGold: "Gold",
      colorGreen: "Green",
      colorCyan: "Cyan",
      colorPurple: "Purple",
      undo: "Undo",
      redo: "Redo",
      fullscreen: "Fullscreen",
      exitFullscreen: "Exit fullscreen",
      clear: "Clear",
      debug: "Debug",
      canvas: "Zoomable handwritten AI canvas",
      aiGuide: "AI knowledge guide",
      openAIMenu: "Open AI action menu",
      aiActions: "AI actions",
      answer: "Answer",
      hint: "Hint",
      continue: "Continue",
      explain: "Explain",
      plot: "Plot",
      tip: "Pan: middle-mouse drag, Hand tool, or one finger · Zoom: wheel or pinch",
      tourReplay: "Feature tour",
      tourDialog: "Lumi6 feature tour",
      tourBadge: "Quick tour",
      tourBadgeNew: "What's new",
      tourProgress: "Tour progress",
      tourStepCounter: "Step {current} of {total}",
      tourSkip: "Skip tour",
      tourBack: "Back",
      tourNext: "Next",
      tourDone: "Finish",
      tourEffortTitle: "Choose how deeply AI reasons",
      tourEffortBody: "AI Effort controls the reasoning depth used for each request. Higher levels suit difficult derivations and multi-step problems, but can take longer. Configured uses the default selected in your local setup.",
      tourPluginsTitle: "Real photos and professional diagrams",
      tourPluginsBody: "Real Photos is on by default and usually shows one web photo. Professional Diagrams is also on by default and creates editable professional visuals with copyable source. Manage both in Plugins.",
      tourHandTitle: "Move objects with the Hand tool",
      tourHandBody: "Choose Hand, then use the small top handle to move outlined images, animations, and AI HTML widgets. Hand also lets you click inside HTML widgets; drag empty space to pan.",
      tourStudioThemeTitle: "Try the new Studio theme",
      tourStudioThemeBody: "Open Theme to switch the canvas's visual style and the AI's response emphasis. The new Studio theme uses a clean, focused interface and favors concise, well-structured, practical answers. You can switch themes at any time.",
      tourLassoTitle: "Work with exactly the content you select",
      tourLassoBody: "With a mouse or stylus, draw a closed loop around handwriting. Drag the selected region to move it; use the right edge, bottom edge, or lower-right corner to resize it. The selection toolbar can typeset handwriting, delete it, or cancel. Selection-scoped AI requests do not reference the rest of the canvas.",
      tourTextTitle: "Add editable text and formulas",
      tourTextBody: "Choose Text, then click the canvas to create an input box. Markdown and likely LaTeX are formatted automatically; Preview shows the exact placement before confirmation. Confirm with the check button or Ctrl/Cmd + Enter.",
      tourImageTitle: "Add images and photos",
      tourImageBody: "Add a picture from your device; large pictures are compressed automatically. In Hand, use its top handle to move it and edge handles to resize. Place keeps it below ink, while Merge makes it erasable.",
      tourFullscreenTitle: "Give the canvas the whole screen",
      tourFullscreenBody: "Fullscreen hides surrounding browser space and expands the drawing area. Use the same button—or your browser's fullscreen shortcut—to return.",
      tourFilesTitle: "Start, export, and save locally",
      tourFilesBody: "New starts a clean canvas and offers to save confirmed work first. Download exports all visible ink as a cropped PNG. History opens local snapshots, where you can name, save, reload, or delete canvases. Unconfirmed AI drafts are not saved.",
      tourManualAITitle: "Ask AI for a specific kind of help",
      tourManualAIBody: "Click the magic orb to open manual AI actions such as Answer, Hint, Continue, Explain, and Plot. Manual requests use the current canvas context—or only the lasso selection when one is active.",
      tourStatusTitle: "Follow every AI request and result",
      tourStatusBody: "This status indicator reports when AI is observing, writing, finished, delayed, or needs confirmation. When a multi-part draft is ready, nearby controls let you accept or discard the complete response.",
      tourCanvasTitle: "Navigate the large canvas",
      tourCanvasBody: "Write with a mouse or stylus. Pan with one finger, the middle mouse button, or Alt-drag. Zoom with a wheel or trackpad, and pinch with two fingers. Your pointer position and zoom level are shown below the canvas.",
      changelogDialog: "Lumi6 release notes",
      changelogClose: "Close release notes",
      changelogBadge: "What's new",
      changelogTitle: "Professional diagrams, editable source, and precise refinement",
      changelogIntro: "Version 0.8.0 expands Lumi6 from flowcharts into professional engineering, scientific, software, and business diagrams.",
      changelogPluginEnableNote: "Professional Diagrams is on by default. You can turn it off at any time from Plugins.",
      changelogVisualPlugins: "Professional Diagrams chooses an appropriate editable domain format. Supported formats render locally in the existing iframe; specialized or unlisted formats can use generated HTML while preserving copyable professional source.",
      changelogCanvasWorkflow: "Draw or describe the professional diagram you need; Lumi6 chooses a suitable format and returns it as a canvas widget.",
      changelogPluginRefine: "Plugin-returned widgets can be refined directly: draw the requested changes over the widget with the Pen, then click the Refine button that appears. This workflow applies only to plugin widgets.",
      changelogDesktopAccess: "Professional Diagrams is second in the plugin list and on by default. Its compact capability guide adds about 1.5k–2k prompt tokens per AI request; full renderer CSS and libraries stay local and load only when needed.",
      changelogEarlierTitle: "Earlier highlights",
      changelogImagesSummary: "0.7.2 added sourced web photos, more reliable canvas persistence and export, and simpler protected local access.",
      changelogPluginsSummary: "0.7.1 added local images and photos with canvas-native editing, snapshots, PNG export, and early copyable flowcharts.",
      changelogAnimation: "0.7.0 introduced sandboxed HTML plugins; 0.6.0 introduced controllable declarative animation scenes.",
      changelogDone: "Got it",
      settingsTitle: "Settings",
      settingsClose: "Close settings",
      settingsAISection: "AI",
      settingsSummonSection: "Thinking indicator",
      settingsSummonEnabled: "Show while AI thinks",
      settingsSummonDescription: "A changing mathematical form and quiet text appear while each request runs.",
      settingsChangelog: "What's new",
      settingsHelpSection: "Help & about",
      settingsDownloadMac: "Download for macOS",
      settingsDownloadWin: "Download for Windows",
      settingsGitHub: "GitHub repository",
      summonPhrase1: "I’m following the trail your pen left behind...",
      summonPhrase2: "Give me a moment—I’m fitting the pieces on the canvas together.",
      summonPhrase3: "This deserves another look. I’m still thinking with you.",
      summonPhrase4: "I’m turning the question around to see its other side...",
      summonPhrase5: "No rush. The answer is beginning to take shape.",
      summonPhrase6: "I’m looking for the most honest explanation between these lines.",
      summonPhrase7: "Thinking is not waiting for an answer; it is making the question clearer.",
      summonPhrase8: "The canvas keeps the marks; understanding gives them direction.",
      summonPhrase9: "Every line is a question that has not quite finished speaking.",
      summonPhrase10: "Intelligence may begin with calculation; understanding begins with attention.",
      summonPhrase11: "Let’s turn this hazy idea into something we can both see.",
      summonPhrase12: "An answer is not an ending. It is where the next stroke begins.",
      summonTip1: "Tip: create professional diagrams for engineering, science, software, and business.",
      summonTip2: "Tip: professional diagrams preserve editable source that you can copy into other tools.",
      summonTip3: "Tip: add a few strokes beside a diagram, then use AI Refine to update only that diagram.",
      summonTip4: "Tip: AI Refine tries to preserve the diagram’s format, layout, terminology, and visual style.",
      summonTip5: "Tip: professional diagram renderers load only when needed; simply viewing them uses no model tokens.",
      summonTip6: "Tip: Professional Diagrams is on by default and can be turned off from Plugins.",
      summonTip7: "Tip: Real Photo Search places sourced web photos directly on the canvas.",
      summonTip8: "Tip: use Hand to move and freely resize images, animations, and AI widgets.",
      summonTip9: "Tip: remote images remain included when you save the canvas or export a PNG.",
      summonTip10: "Tip: save a canvas to the Lumi6 server so other authorized devices can open it.",
      summonTip11: "Tip: pause a few seconds after writing and AI replies on its own; auto mode can be toggled in Settings.",
      summonTip12: "Tip: click the AI orb on the canvas to manually pick Answer, Hint, Continue, Explain, or Plot.",
      summonTip13: "Tip: circle content with the lasso and AI will work only on that selection.",
      summonTip14: "Tip: the text tool understands Markdown and LaTeX; press Ctrl/Cmd + Enter to confirm.",
      summonTip15: "Tip: AI drafts can be moved as a group, or accepted and discarded item by item.",
      summonTip16: "Tip: raise the Reasoning effort in the toolbar for harder problems.",
      summonTip17: "Tip: plugins add focused capabilities and can be switched off when you do not need them.",
      summonTip18: "Tip: History can update the current snapshot or save a separate new copy.",
      summonTip19: "Tip: zoom with the wheel, pan with the middle mouse button—the canvas spans twenty thousand squares.",
      summonTip20: "Tip: AI ink color lives in the toolbar; AI font lives in this Settings panel.",
      debugTitle: "Lumi6 debug",
      openLocalLog: "Open local server log",
      history: "Canvas history",
      historyTitle: "Canvas history",
      historyDescription: "Stores confirmed canvas content, including restorable animation scenes. Unconfirmed AI drafts are excluded.",
      saveLocation: "Save location",
      storageThisDevice: "This device",
      storageLumi6Server: "Lumi6 server",
      storageThisDeviceDescription: "Saved only in this browser on this device. Other devices cannot see it.",
      storageLumi6ServerDescription: "Saved on the computer running Lumi6. Anyone using this Lumi6 service can see it after passing its access check.",
      closeHistory: "Close history",
      newCanvas: "New",
      saveCanvas: "Save canvas",
      saveCurrentSnapshot: "Save",
      exportPng: "Export PNG",
      newCanvasTitle: "Start a new canvas?",
      newCanvasDescription: "Save confirmed content and animation scenes before starting over. Unconfirmed AI drafts are not included.",
      currentSnapshot: "Current snapshot: {name} · {location}",
      noCurrentSnapshot: "There is no current snapshot to overwrite.",
      currentSnapshotOtherLocation: "Current snapshot {name} is in {location}. Select that location to overwrite it.",
      newSnapshotName: "Name for new snapshot (optional)",
      cancel: "Cancel",
      newWithoutSave: "Don't save",
      saveAsNewAndCreate: "Save as new",
      overwriteAndCreate: "Overwrite current",
      snapshotName: "Snapshot name (optional)",
      saveSnapshot: "Save New",
      snapshotSaving: "Saving canvas...",
      snapshotSavingShort: "Saving...",
      loadSnapshot: "Load",
      deleteSnapshot: "Delete",
      emptyDeviceHistory: "No canvases saved on this device yet",
      emptyServerHistory: "No canvases saved on this Lumi6 server yet",
      emptyCanvas: "The canvas is empty",
      snapshotSaved: "Canvas snapshot saved",
      snapshotOverwritten: "Current snapshot overwritten",
      snapshotLoaded: "Canvas snapshot loaded",
      snapshotDeleted: "Canvas snapshot deleted",
      newCanvasReady: "New canvas ready",
      exportComplete: "PNG exported",
      exportError: "Export: ",
      snapshotError: "Canvas history: ",
      snapshotTiles: "canvas tiles",
      snapshotImages: "images",
      deleteSnapshotConfirmDevice: "Delete this snapshot from this device?",
      deleteSnapshotConfirmServer: "Delete this shared snapshot from the Lumi6 server?",
      footerTip: "AI drafts: move the whole group or adjust, accept, and discard items independently",
      ready: "Ready",
      aiBusy: "AI is working. Please wait.",
      noInk: "Write something first",
      cannotCapture: "Could not capture the newest handwriting",
      observing: "Observing...",
      deferred: "New ink found; this AI result was deferred",
      writing: "Writing...",
      aiDone: "AI complete",
      draftRejected: "AI draft discarded",
      draftFading: "Continued writing detected; fading the AI draft",
      canvasChanged: "Canvas changed; the old AI draft was discarded",
      draftReady: "Drag the AI draft to move it; use its handles to resize",
      batchDraftReady: "Drag an item to move it; drag the group frame or blank space to move all; use the group corner to resize",
      itemAccepted: "AI item accepted; remaining drafts are still editable",
      itemDiscarded: "AI item discarded; remaining drafts are still editable",
      copyText: "Copy content",
      textCopied: "Copied",
      textCopyFailed: "Could not copy content",
      rejectBatch: "Discard all AI drafts",
      acceptBatch: "Accept all AI drafts",
      outsideCanvas: "This is outside the canvas. Write on the paper.",
      selectionEmpty: "The selected area has no ink",
      selectionTooSmall: "Draw a larger closed lasso around some ink",
      selectionReady: "Move or resize the selected lasso region",
      selectionCommitted: "Selection applied locally",
      selectionCancelled: "Selection cancelled",
      selectionRecolored: "Selection color changed locally",
      selectionTools: "Selection tools",
      selectionScopeNotice: "AI answers use only this selected region",
      selectionTypeset: "Typeset",
      selectionDelete: "Delete",
      selectionCancel: "Cancel",
      selectionTypesetting: "Typesetting selection...",
      selectionDeleted: "Selected region deleted",
      pendingConfirm: "Confirm or discard the current AI draft first",
      merged: "AI merged",
      plugins: "Plugins",
      pluginManagerTitle: "Plugin manager",
      pluginManagerDescription: "Choose which capabilities the AI can use. Disabled plugins add no prompt or canvas widget runtime.",
      closePlugins: "Close plugins",
      pluginSources: "Plugin sources",
      localPlugins: "Local plugins",
      createPlugin: "Create",
      pluginPreview: "Preview",
      serverPlugins: "Server plugins",
      comingSoon: "Coming soon",
      refreshPlugins: "Refresh local plugins",
      serverPluginsComingTitle: "Server plugin marketplace is coming",
      serverPluginsComingDescription: "Published plugins, free or points-priced downloads, server selection, trust details, and updates will appear here after the Lumi6 website launches.",
      pluginBuiltIn: "Built in",
      pluginLocal: "Local Markdown",
      pluginPersonalSection: "Your plugins",
      pluginBuiltInSection: "Built-in plugins",
      pluginRecommended: "Recommended",
      generalPluginRecommendedHelp: "Recommended. Gives AI a flexible way to present rich interactive and dynamic content when ordinary canvas output is not enough.",
      pluginUsageTitle: "How to use",
      pluginUsageDescription: "For custom interfaces, enable General HTML and write a request such as “a colorful live clock.” For live data, enable its source and ask for “Shanghai weather” or “Kweichow Moutai daily chart.” An arrow or box can choose where the widget appears; data is fetched directly by your browser.",
      pluginSourceLabel: "Source: {source}",
      pluginApiLabel: "API: {origins}",
      pluginNoNetwork: "No network access",
      pluginPromptEstimate: "adds about {tokens} prompt tokens to each AI request while enabled; once on canvas, display, interaction, refresh, and rendering use no tokens",
      pluginRefreshRate: "refresh {time}",
      pluginDetails: "Details",
      pluginDetailsFor: "{name} plugin details",
      copyPluginMarkdown: "Copy Markdown",
      pluginMarkdownCopied: "Copied",
      pluginMarkdownCopyFailed: "Copy failed",
      duplicatePlugin: "Create editable copy",
      pluginCopyName: "Copy of {name}",
      pluginCopyDraftReady: "Editable copy of {name} is ready. Review and save it as your own plugin.",
      pluginBuiltInRuntime: "Built-in runtime capability",
      pluginDefaultState: "Default: {state}",
      pluginRequestField: "Request field: {field}",
      pluginStateEnabled: "enabled",
      pluginStateDisabled: "disabled",
      pluginMinute: "{count} min",
      pluginHour: "{count} hr",
      pluginDay: "{count} day",
      pluginCatalogLoading: "Refreshing local plugin directory...",
      pluginCatalogReady: "{count} plugins found · {enabled} enabled",
      pluginCatalogFailed: "Local plugin directory could not be refreshed",
      pluginNoDescription: "Local plugin capability",
      createPluginTitle: "Create a local plugin",
      createPluginDescription: "Preview: this workflow has limited testing. Describe the capability in the template, then preferably use Improve with AI before saving so endpoints, runtime rules, and the display title are completed for you.",
      sharePluginComing: "Share for points · Coming soon",
      pluginTemplateLabel: "Template",
      pluginSimpleTemplate: "Simple HTML",
      pluginTitleLabel: "Plugin title",
      pluginTitlePlaceholder: "Filled automatically by Improve with AI, or enter your own",
      pluginDocumentLabel: "Plugin Markdown",
      pluginDocumentHint: "Prefer Improve with AI before saving. The final document needs frontmatter and an exact One-shot example.",
      pluginStylesLabel: "Plugin CSS (optional)",
      pluginStylesHint: "Saved CSS is injected only when this plugin's widget is mounted; it does not load at canvas startup. Edit here or import a .css file. Put external JS/CSS URLs in generated widget HTML.",
      pluginStylesImport: "Import .css",
      pluginStylesImported: "Imported {name}. Review the preview before saving.",
      pluginStylesFileType: "Choose a .css file",
      pluginStylesFileTooLarge: "CSS file must be 32000 bytes or smaller",
      pluginStylesReadFailed: "CSS file could not be read: {error}",
      pluginStylesPreview: "Plugin CSS preview",
      improvePluginWithAi: "Improve with AI",
      saveAndEnablePlugin: "Save and enable",
      pluginMarketplaceNote: "The future marketplace will support free or points-priced downloads. Authors will be able to share plugins and earn points.",
      pluginBytes: "{bytes} / 12000 bytes",
      pluginStylesBytes: "{bytes} / 32000 bytes",
      pluginDraftValid: "Ready to save as {name}",
      pluginDraftInvalid: "Fix the plugin document: {error}",
      pluginIdExists: "Plugin id {id} already exists",
      pluginIdReserved: "Plugin id {id} is reserved",
      pluginImproving: "AI is improving the capability contract...",
      pluginImproved: "AI improvement is ready. Review it before saving.",
      pluginImproveFailed: "AI improvement failed: {error}",
      pluginSaving: "Saving local plugin...",
      pluginSaved: "{name} was saved and enabled",
      pluginSaveFailed: "Plugin could not be saved: {error}",
      deletePlugin: "Delete plugin",
      deletePluginConfirm: "Delete the local plugin “{name}”? Existing widgets created with it will stop running.",
      pluginDeleting: "Deleting {name}...",
      pluginDeleted: "{name} was deleted",
      pluginDeleteFailed: "Plugin could not be deleted: {error}",
      animationPlugin: "Animation scenes",
      animationPluginCost: "Adds about 500–600 prompt tokens per AI request",
      animationPluginDisabledHelp: "When enabled, the model can return animated demonstrations when explicitly requested or genuinely useful.",
      animationControls: "Animation controls",
      animationPlay: "Play",
      animationPause: "Pause",
      animationRestart: "Restart",
      animationDelete: "Delete animation",
      animationSelected: "Editing animation; drag the top handle to move, resize with edge or corner handles, then confirm or cancel",
      animationDeleted: "Animation deleted",
      animationLimitReached: "Animation limit reached (100). Delete an animation before adding another.",
      snapshotAnimations: "animations",
      widgetAccept: "Keep widget",
      widgetDiscard: "Discard widget",
      widgetMove: "Move widget",
      widgetDelete: "Delete widget",
      widgetDeleted: "Widget deleted",
      widgetSourceCopied: "Widget source copied",
      widgetSourceCopyFailed: "Widget source could not be copied",
      widgetRefine: "AI Refine",
      widgetRefineHint: "Refine and replace this widget using its content and the current canvas",
      widgetRefinePending: "New marks detected near this diagram. Use its AI Refine button to update it, or choose a manual AI action above. Auto AI is paused.",
      widgetRefining: "AI is refining this widget",
      widgetReplacementReady: "Review the refined replacement",
      widgetExportFailed: "A live widget could not be captured. Wait for it to finish loading and try again.",
      widgetPluginUnavailable: "The plugin document could not be loaded",
      widgetLimitReached: "Live widget limit reached (100). Delete a widget before adding another.",
      snapshotWidgets: "live widgets",
      clearConfirm: "Clear the whole canvas?",
      timeout: "Request timed out",
      aiNoVisibleResponse: "AI returned no displayable content. Please retry or rephrase the request.",
    },
  };
  const PLUGIN_STORAGE_KEY = "lumi6-plugins",
    DIAGRAM_RUNTIME_VERSION = "lumi6-diagram-source-v1",
    DIAGRAM_SOURCE_FORMATS = new Set(["mermaid", "dot", "bpmn-xml", "vega-lite", "geojson", "smiles", "cytoscape-json"]),
    BUILTIN_PLUGIN_DEFINITIONS = Object.freeze([
      Object.freeze({
        id: "animation",
        labelKey: "animationPlugin",
        costKey: "animationPluginCost",
        helpKey: "animationPluginDisabledHelp",
        requestField: "animationEnabled",
        builtIn: true,
        defaultEnabled: true,
        legacyStorageKey: "lumi6-animation-plugin",
        onChange: applyAnimationPluginState,
      }),
    ]);
  const PLUGIN_DEFINITIONS = [...BUILTIN_PLUGIN_DEFINITIONS];
  const pluginManifests = new Map(),
    pluginLoadErrors = new Map(),
    widgetSnapshotRequests = new Map(),
    widgetHostPointerAnchors = new Map(),
    screenCalibration = new Map();
  let diagramRuntimePromise = null;
  let screenClientRatio = 1;
  function storedPluginSettings() {
    let stored = {};
    try {
      const parsed = JSON.parse(localStorage.getItem(PLUGIN_STORAGE_KEY) || "{}");
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) stored = parsed;
    } catch {}
    return Object.fromEntries(PLUGIN_DEFINITIONS.map((plugin) => {
      const legacy = plugin.legacyStorageKey ? localStorage.getItem(plugin.legacyStorageKey) : null,
        value = typeof stored[plugin.id] === "boolean" ? stored[plugin.id] : legacy === null ? plugin.defaultEnabled : legacy === "true";
      return [plugin.id, value];
    }));
  }
  const initialPlugins = storedPluginSettings();
  const storedPrimaryLanguage = localStorage.getItem("lumi6-language"),
    storedLegacyLanguage = localStorage.getItem("ghostboard-language"),
    storedTheme = localStorage.getItem("lumi6-theme") || localStorage.getItem("ghostboard-theme"),
    storedGrid = localStorage.getItem("lumi6-grid") ?? localStorage.getItem("ghostboard-grid"),
    storedResearchGrid = localStorage.getItem("lumi6-research-grid"),
    storedAutoEnabled = localStorage.getItem("lumi6-auto-ai"),
    storedAutoDelayText = localStorage.getItem("lumi6-auto-delay-ms"),
    storedSummonEnabled = localStorage.getItem("lumi6-summon-enabled"),
    storedSnapshotLocation = localStorage.getItem("lumi6-snapshot-location"),
    storedAiEffortText = String(localStorage.getItem("lumi6-ai-effort") || "").trim().toLowerCase(),
    storedAiEffort = storedAiEffortText === "xhigh" ? "max" : storedAiEffortText,
    storedAutoDelay = storedAutoDelayText === null ? NaN : Number(storedAutoDelayText),
    initialLanguage = TOUR.resolveInitialLanguage(storedPrimaryLanguage, storedLegacyLanguage),
    initialTheme = ["arcane", "scifi", "research", "studio", "indic"].includes(storedTheme) ? storedTheme : "studio",
    initialGrid = storedGrid === null ? true : storedGrid === "true",
    initialResearchGrid = storedResearchGrid === "true",
    configuredAutoDelay = Number(window.LUMI6_CONFIG?.autoAiDelayMs),
    configuredAiTimeout = Number(window.LUMI6_CONFIG?.aiRequestTimeoutMs),
    configuredAiEffort = String(window.LUMI6_CONFIG?.aiEffort || "").trim().toLowerCase(),
    configuredAccessSession = String(window.LUMI6_CONFIG?.accessSessionToken || sessionStorage.getItem("lumi6-access-session") || ""),
    serverAutoDelay = Number.isFinite(configuredAutoDelay) && configuredAutoDelay >= 0 ? configuredAutoDelay : DEFAULT_AUTO_DELAY,
    initialAutoDelay = Number.isFinite(storedAutoDelay) && storedAutoDelay >= 0 && storedAutoDelay <= 10000 ? storedAutoDelay : Math.min(10000, serverAutoDelay),
    initialAutoEnabled = false,
    initialSummonEnabled = storedSummonEnabled === null ? true : storedSummonEnabled === "true",
    initialSnapshotLocation = storedSnapshotLocation === "server" ? "server" : "device",
    initialAiEffort = EFFORT_OPTIONS.includes(storedAiEffort) ? storedAiEffort : EFFORT_OPTIONS.includes(configuredAiEffort) ? configuredAiEffort : "config",
    initialAiTimeout = Number.isFinite(configuredAiTimeout) && configuredAiTimeout >= 10000 ? configuredAiTimeout : DEFAULT_AI_TIMEOUT;
  function authenticatedApiHeaders(headers = {}) {
    return configuredAccessSession ? { ...headers, "X-Lumi6-Session":configuredAccessSession } : { ...headers };
  }
  const tiles = new Map(),
    state = {
      mode: "pen",
      scale: 0.1,
      panX: 0,
      panY: 0,
      pen: 6,
      eraser: 35,
      aiFont: "ui-rounded, system-ui, sans-serif",
      inkColor: "#2563eb",
      aiColor: "#2563eb",
      drawing: null,
      pointers: new Map(),
      touches: new Map(),
      touchGesture: null,
      panGesture: null,
      textEditors: new Map(),
      textBoxes: [],
      textEditorStyleSheet: null,
      nextTextEditorId: 1,
      nextTextBoxId: 1,
      nextTextEditorZ: 1,
      activeTextEditorId: null,
      selectedTextBoxId: null,
      textBoxHistoryBefore: null,
      animations: [],
      nextAnimationId: 1,
      selectedAnimationId: null,
      animationGesture: null,
      animationEdit: null,
      widgets: [],
      nextWidgetId: 1,
      pendingWidget: null,
      pendingWidgetReplacement: null,
      selectedWidgetId: null,
      widgetEdit: null,
      widgetGesture: null,
      widgetHostPan: null,
      widgetHistoryBefore: null,
      widgetRefineCandidate: null,
      widgetMessageHooked: false,
      plugins: { ...initialPlugins },
      animationFrame: 0,
      animationLastFrame: 0,
      animationFullRedraw: true,
      animationScreenBoxes: new Map(),
      animationRenderedPlayheads: new Map(),
      animationControlsTimer: 0,
      animationControlsUntil: 0,
      interactionRenderQueued: false,
      animationHistoryBefore: null,
      sharpOverlays: [],
      sharpOverlayPixels: 0,
      images: [],
      nextImageId: 1,
      selectedImageId: null,
      imageEdit: null,
      imageGesture: null,
      imageHistoryBefore: null,
      imageHandReturnMode: null,
      imageImporting: false,
      clipboardImporting: false,
      textInputBlockedUntil: 0,
      textTap: null,
      latestTypedInput: null,
      pending: null,
      pendingGesture: null,
      aiDraftReturnMode: null,
      pendingHistoryRestored: false,
      pointerPreview: null,
      copyGeneration: 0,
      selection: null,
      selectionGesture: null,
      hotspotTrail: [],
      auto: initialAutoEnabled,
      summonEnabled: initialSummonEnabled,
      summonAnchor: null,
      timer: 0,
      autoPopoverTimer: 0,
      effortPopoverTimer: 0,
      pluginCatalogLoading: false,
      pluginCatalogLoaded: false,
      pluginCatalogError: "",
      pluginCatalogNotice: null,
      pluginDeleting: "",
      pluginDialogRestoreFocus: null,
      pluginAuthoringTemplate: "simple",
      pluginAuthoringBusy: false,
      pluginAuthoringStatus: null,
      autoDelayMs: initialAutoDelay,
      reasoningEffort: initialAiEffort,
      aiRequestTimeoutMs: initialAiTimeout,
      dirty: null,
      autoEligible: false,
      lastUserBox: null,
      history: [],
      future: [],
      historyBefore: new Map(),
      inkBounds: new Map(),
      busy: false,
      activeAI: null,
      snapshotLoadGeneration: 0,
      snapshotLocation: initialSnapshotLocation,
      currentSnapshotId: null,
      currentSnapshotName: "",
      currentSnapshotLocation: null,
      restoreGeneration: 0,
      recognitionGeneration: 0,
      userRevision: 0,
      lastRequestId: "—",
      viewInitialized: false,
      renderQueued: false,
      language: initialLanguage,
      theme: initialTheme,
      gridVisible: initialTheme === "research" ? initialResearchGrid : initialGrid,
      paint: { paper: "#ffffff", paperGrid: "rgba(0, 0, 0, 0.05)", outside: "#ffffff", border: "#e2e8f0" },
      navigationTimer: 0,
      radialGesture: null,
      radialCloseTimer: 0,
      radialSuppressClickUntil: 0,
      statusKey: "ready",
    };
  let textHelpInvoker = null;
  let pluginStylesPreviewReady = false,
    pluginStylesPreviewPayload = null;
  const AI_CANCELLED = "AI_CANCELLED";
  const AI_REJECTED = "AI_REJECTED";
  const AI_SUPERSEDED = "AI_SUPERSEDED";
  const FEATURE_TOUR_STORAGE_KEY = "lumi6-tour-progress";
  const CHANGELOG_STORAGE_KEY = "lumi6-changelog-seen";
  const CHANGELOG_VERSION = "0.8.0";
  // Keep seen IDs stable. Add a new ID (or bump its -vN suffix) to show only that feature to returning users.
  const FEATURE_TOUR_STEPS = Object.freeze([
    { id: "core-effort-v1", targets: ["#aiEffortButton"], titleKey: "tourEffortTitle", bodyKey: "tourEffortBody", placement: "bottom", radius: 8 },
    { id: "plugins-v3", targets: ["#pluginButton"], titleKey: "tourPluginsTitle", bodyKey: "tourPluginsBody", placement: "bottom", radius: 8 },
    { id: "hand-v1", targets: ["#handToolBtn"], titleKey: "tourHandTitle", bodyKey: "tourHandBody", placement: "bottom", radius: 7 },
    { id: "studio-theme-v1", targets: ["#theme"], titleKey: "tourStudioThemeTitle", bodyKey: "tourStudioThemeBody", placement: "bottom", radius: 8 },
    { id: "core-lasso-v1", targets: ["#lassoToolBtn"], titleKey: "tourLassoTitle", bodyKey: "tourLassoBody", placement: "bottom", radius: 7 },
    { id: "core-text-v1", targets: ["#textToolBtn"], titleKey: "tourTextTitle", bodyKey: "tourTextBody", placement: "bottom", radius: 7 },
    { id: "core-image-v1", targets: ["#imagePickerBtn"], titleKey: "tourImageTitle", bodyKey: "tourImageBody", placement: "bottom", radius: 7 },
    { id: "core-fullscreen-v1", targets: ["#fullscreenBtn"], titleKey: "tourFullscreenTitle", bodyKey: "tourFullscreenBody", placement: "bottom", radius: 7 },
    { id: "core-files-v1", targets: ["#canvasFileActions"], titleKey: "tourFilesTitle", bodyKey: "tourFilesBody", placement: "bottom", radius: 8 },
    { id: "core-manual-ai-v1", targets: ["#aiOrb"], titleKey: "tourManualAITitle", bodyKey: "tourManualAIBody", placement: "left", radius: 50 },
    { id: "core-status-v1", targets: ["#aiStatusArea"], titleKey: "tourStatusTitle", bodyKey: "tourStatusBody", placement: "bottom", radius: 999 },
    { id: "core-navigation-v1", targets: ["#viewport"], titleKey: "tourCanvasTitle", bodyKey: "tourCanvasBody", placement: "center", radius: 10, padding: 5 },
  ]);
  const featureTour = {
    active: false,
    steps: [],
    index: 0,
    progress: TOUR.parseProgress(null),
    replay: false,
    newOnly: false,
    restoreFocus: null,
    restoreScrollX: 0,
    restoreScrollY: 0,
    positionFrame: 0,
    retryFrame: 0,
    resizeObserver: null,
    pendingObserver: null,
    activeObserver: null,
    targets: [],
    shownIds: new Set(),
    autoChecked: false,
  };
  const changelog = {
    active: false,
    restoreFocus: null,
  };
  const COLOR_CLASS = { "#2563eb": "color-blue", "#1f2937": "color-black", "#dc2626": "color-red", "#ea580c": "color-orange", "#ca8a04": "color-gold", "#16a34a": "color-green", "#0891b2": "color-cyan", "#9333ea": "color-purple" };
  const runtimeStyleRules = new Map();
